### ISSUE TITLE
Bug in models.py - name Error

### ISSUE THREAD

**Issue by Clarkclayton** [adle29/cs373-idb#18]
Traceback (most recent call last):
  File "apps/models.py", line 111, in <module>
    class Standing(Base):
  File "apps/models.py", line 129, in Standing
    Rseason = relationship("Season", back_populates=Sstanding) #many to 1
NameError: name 'Sstanding' is not defined

**Comment by Clarkclayton** [comment]
followed this model for creating the relationships: 

class Parent(Base):
    **tablename** = 'parent'
    id = Column(Integer, primary_key=True)
    child_id = Column(Integer, ForeignKey('child.id'))
    child = relationship("Child", back_populates="parents")

class Child(Base):
    **tablename** = 'child'
    id = Column(Integer, primary_key=True)
    parents = relationship("Parent", back_populates="child")

took out back_populates with the parent and it works now
